This notebook (and the slides from lecture 8) will help you go straight from training a model in Colab to deploying it in a webpage with TensorFlow.js - without having to leave the browser.

Configure this notebook to work with your GitHub account by populating these fields.

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import keras
from keras import Sequential
from keras.layers import Flatten, MaxPool2D, Conv2D, Conv1D, GlobalMaxPooling1D, MaxPooling1D ,Dense, LSTM, RNN, Dropout, GRU, Embedding
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

from sklearn.model_selection import train_test_split
# import tensorflowjs


In [40]:
!pip install tensorflowjs

    100% |████████████████████████████████| 51kB 8.7MB/s 
tensorflow 1.12.0 has requirement keras-applications>=1.0.6, but you'll have keras-applications 1.0.4 which is incompatible.
tensorflow 1.12.0 has requirement keras-preprocessing>=1.0.5, but you'll have keras-preprocessing 1.0.2 which is incompatible.
  Found existing installation: Keras-Preprocessing 1.0.5
    Uninstalling Keras-Preprocessing-1.0.5:
      Successfully uninstalled Keras-Preprocessing-1.0.5
  Found existing installation: Keras-Applications 1.0.6
    Uninstalling Keras-Applications-1.0.6:
      Successfully uninstalled Keras-Applications-1.0.6


As an example, we will create and vectorize a few documents. (Check out https://www.gutenberg.org/ for a bunch of free e-books.)

In [0]:
# A few snippets from Alice in Wonderland
ex1 = "Alice was beginning to get very tired of sitting by her sister on the bank."
ex2 = "Once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it."

# Dracula
ex3 = "Buda-Pesth seems a wonderful place."
ex4 = "Left Munich at 8:35 P. M., on 1st May, arriving at Vienna early next morning."

# Illiad
ex5 = "Scepticism was as much the result of knowledge, as knowledge is of scepticism."
ex6 = "To be content with what we at present know, is, for the most part, to shut our ears against conviction."

In [0]:
x_train = [ex1, ex2, ex3, ex4, ex5, ex6]
y_train = [0, 0, 1, 1, 2, 2] # Indicating which book each sentence is from

Tokenize the documents, create a word index (word -> number).

In [0]:
max_len = 20
num_words = 1000
# Fit the tokenizer on the training data
t = Tokenizer(num_words=num_words)
t.fit_on_texts(x_train)

Using TensorFlow backend.


In [0]:
print(t.word_index)

{'the': 1, 'was': 2, 'to': 3, 'of': 4, 'at': 5, 'her': 6, 'sister': 7, 'on': 8, 'or': 9, 'had': 10, 'it': 11, 'scepticism': 12, 'as': 13, 'knowledge': 14, 'is': 15, 'alice': 16, 'beginning': 17, 'get': 18, 'very': 19, 'tired': 20, 'sitting': 21, 'by': 22, 'bank': 23, 'once': 24, 'twice': 25, 'she': 26, 'peeped': 27, 'into': 28, 'book': 29, 'reading': 30, 'but': 31, 'no': 32, 'pictures': 33, 'conversations': 34, 'in': 35, 'buda': 36, 'pesth': 37, 'seems': 38, 'a': 39, 'wonderful': 40, 'place': 41, 'left': 42, 'munich': 43, '8': 44, '35': 45, 'p': 46, 'm': 47, '1st': 48, 'may': 49, 'arriving': 50, 'vienna': 51, 'early': 52, 'next': 53, 'morning': 54, 'much': 55, 'result': 56, 'be': 57, 'content': 58, 'with': 59, 'what': 60, 'we': 61, 'present': 62, 'know': 63, 'for': 64, 'most': 65, 'part': 66, 'shut': 67, 'our': 68, 'ears': 69, 'against': 70, 'conviction': 71}


Here's how we vectorize a document.

In [0]:
vectorized = t.texts_to_sequences([ex1])
print(vectorized)

[[16, 2, 17, 3, 18, 19, 20, 4, 21, 22, 6, 7, 8, 1, 23]]


Apply padding if necessary.

In [0]:
padded = pad_sequences(vectorized, maxlen=max_len, padding='post')

In [0]:
print(padded)

[[16  2 17  3 18 19 20  4 21 22  6  7  8  1 23  0  0  0  0  0]]


We will save the word index in metadata. Later, we'll use it to convert words typed in the browser to numbers for prediction.

In [0]:
metadata = {
  'word_index': t.word_index,
  'max_len': max_len,
  'vocabulary_size': num_words,
}

Define a model.

In [0]:
embedding_size = 8
n_classes = 3
epochs = 10

model = keras.Sequential()
model.add(keras.layers.Embedding(num_words, embedding_size, input_shape=(max_len,)))
model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(3, activation='softmax'))
model.compile('adam', 'sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 20, 8)             8000      
_________________________________________________________________
flatten_1 (Flatten)          (None, 160)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 483       
Total params: 8,483
Trainable params: 8,483
Non-trainable params: 0
_________________________________________________________________


Prepare some training data.

In [0]:
x_train = t.texts_to_sequences(x_train)
x_train = pad_sequences(x_train, maxlen=max_len, padding='post')
print(x_train)

[[16  2 17  3 18 19 20  4 21 22  6  7  8  1 23  0  0  0  0  0]
 [25 26 10 27 28  1 29  6  7  2 30 31 11 10 32 33  9 34 35 11]
 [36 37 38 39 40 41  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [42 43  5 44 45 46 47  8 48 49 50  5 51 52 53 54  0  0  0  0]
 [12  2 13 55  1 56  4 14 13 14 15  4 12  0  0  0  0  0  0  0]
 [ 3 57 58 59 60 61  5 62 63 15 64  1 65 66  3 67 68 69 70 71]]


In [0]:
model.fit(x_train, y_train, epochs=epochs)

Epoch 1/10
6/6 [==============================] - 1s 97ms/step - loss: 1.1102 - acc: 0.3333
Epoch 2/10
6/6 [==============================] - 0s 1ms/step - loss: 1.0996 - acc: 0.3333
Epoch 3/10
6/6 [==============================] - 0s 333us/step - loss: 1.0891 - acc: 0.3333
Epoch 4/10
6/6 [==============================] - 0s 237us/step - loss: 1.0786 - acc: 0.5000
Epoch 5/10
6/6 [==============================] - 0s 655us/step - loss: 1.0682 - acc: 0.6667
Epoch 6/10
6/6 [==============================] - 0s 771us/step - loss: 1.0578 - acc: 0.8333
Epoch 7/10
6/6 [==============================] - 0s 715us/step - loss: 1.0474 - acc: 0.8333
Epoch 8/10
6/6 [==============================] - 0s 568us/step - loss: 1.0371 - acc: 1.0000
Epoch 9/10
6/6 [==============================] - 0s 306us/step - loss: 1.0267 - acc: 1.0000
Epoch 10/10
6/6 [==============================] - 0s 301us/step - loss: 1.0164 - acc: 1.0000


Demo using the model to make predictions.

In [0]:
test_example = "Left Munich at 8:35 P. M., on 1st May, arriving at Vienna early next morning."
x_test = t.texts_to_sequences([test_example])
x_test = pad_sequences(x_test, maxlen=max_len, padding='post')
print(x_test)

[[42 43  5 44 45 46 47  8 48 49 50  5 51 52 53 54  0  0  0  0]]


In [0]:
preds = model.predict(x_test)
print(preds)
import numpy as np
print(np.argmax(preds))

[[0.32128462 0.37047485 0.3082405 ]]
1


In [0]:
!ls

index.html  index.js  model_js


All done! Hopefully everything worked. You may need to wait a few moments for the changes to appear in your site. If not working, check the JavaScript console for errors (in Chrome: View -> Developer -> JavaScript Console).

In [0]:
print("Now, visit https://%s.github.io/%s/" % (USER_NAME, SITE_NAME))

Now, visit https://Srinidhi-kv.github.io/deep_learning_hw4/


If you are debugging and Chrome is failing to pick up your changes, though you've verified they're present in your GitHub repo, see the second answer to: https://superuser.com/questions/89809/how-to-force-refresh-without-cache-in-google-chrome

## Adding Three books from Gutenberg

In [0]:
from urllib.request import urlopen 

url1 = "http://www.gutenberg.org/files/120/120-0.txt" #Treasure Island
url2 = "http://www.gutenberg.org/files/1184/1184-0.txt" #Count of Mote Cristo
url3 = "http://www.gutenberg.org/cache/epub/1661/pg1661.txt" #Sherlock Holmes

raw1 = urlopen(url1).read().decode('utf-8')
raw2 = urlopen(url2).read().decode('utf-8')
raw3 = urlopen(url3).read().decode('utf-8')

In [0]:
def clean_books(book_url, lines, label):
  
  book = urlopen(book_url).read().decode('utf-8')
  book_clean= book.replace('\r\n', '')
  
  
  x_split = book_clean.split('.')[1000:2000+lines]
  x_train=[]
  
  i=0
  for line in x_split:
    if i>=lines:
      break
    if len(line)>10:
      x_train.append(line)
      i+=1
  
  y_train = list(np.full(lines, label))
  
  return x_train, y_train

In [0]:
x_train1, y_train1= clean_books(url1, 2500, 0)
x_train2, y_train2= clean_books(url2, 2500, 1)
x_train3, y_train3= clean_books(url3, 2500, 2)

In [44]:
len(x_train1)

2500

In [0]:
x_train1.extend(x_train2)
x_train1.extend(x_train3)
y_train1.extend(y_train2)
y_train1.extend(y_train3)


In [46]:
len(y_train1)

7500

In [0]:
x_train, x_test, y_train, y_test = train_test_split(x_train1, y_train1, test_size=0.15, random_state=4356)

In [0]:
max_len = 20
num_words = 2000
# Fit the tokenizer on the training data
t = Tokenizer(num_words=num_words)
t.fit_on_texts(x_train)

In [0]:
x_train = t.texts_to_sequences(x_train)
x_train = pad_sequences(x_train, maxlen=max_len, padding='post')
# print(x_train)

In [0]:
x_test = t.texts_to_sequences(x_test)
x_test = pad_sequences(x_test, maxlen=max_len, padding='post')

### Vanilla Model

In [0]:
optimizer = keras.optimizers.Adam(lr=0.001)

In [0]:
callback = keras.callbacks.EarlyStopping(monitor='val_loss', min_delta=0, patience=1)

In [148]:
embedding_size = 16
n_classes = 3
epochs = 30

model = keras.Sequential()
model.add(keras.layers.Embedding(num_words, embedding_size, input_shape=(max_len,)))
model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(3, activation='softmax'))
model.compile(optimizer, 'sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_28 (Embedding)     (None, 20, 16)            32000     
_________________________________________________________________
flatten_7 (Flatten)          (None, 320)               0         
_________________________________________________________________
dense_24 (Dense)             (None, 3)                 963       
Total params: 32,963
Trainable params: 32,963
Non-trainable params: 0
_________________________________________________________________


In [0]:
callback = keras.callbacks.EarlyStopping(monitor='val_loss', min_delta=0, patience=1)

In [150]:
model.fit(x_train, np.array(y_train), epochs= 50, validation_split=0.15, callbacks=[callback])

Train on 5418 samples, validate on 957 samples
Epoch 1/50
5418/5418 [==============================] - 4s 780us/step - loss: 1.0854 - acc: 0.4105 - val_loss: 1.0585 - val_acc: 0.5329
Epoch 2/50
5418/5418 [==============================] - 1s 164us/step - loss: 0.9624 - acc: 0.6764 - val_loss: 0.8900 - val_acc: 0.6782
Epoch 3/50
5418/5418 [==============================] - 1s 156us/step - loss: 0.7280 - acc: 0.7794 - val_loss: 0.7069 - val_acc: 0.7262
Epoch 4/50
5418/5418 [==============================] - 1s 161us/step - loss: 0.5409 - acc: 0.8422 - val_loss: 0.6020 - val_acc: 0.7638
Epoch 5/50
5418/5418 [==============================] - 1s 157us/step - loss: 0.4217 - acc: 0.8839 - val_loss: 0.5470 - val_acc: 0.7827
Epoch 6/50
5418/5418 [==============================] - 1s 161us/step - loss: 0.3405 - acc: 0.9085 - val_loss: 0.5225 - val_acc: 0.7921
Epoch 7/50
5418/5418 [==============================] - 1s 164us/step - loss: 0.2825 - acc: 0.9265 - val_loss: 0.5033 - val_acc: 0.8036
E

In [157]:
model.evaluate(x_test, np.array(y_test))

1125/1125 [==============================] - 0s 77us/step


[0.4806314495404561, 0.7866666667196486]

In [0]:
model.save('books_classification_embedding.h5')

#### Vanilla Model Test Accuracy: 79%

### LSTM Model

In [0]:
optimizer = keras.optimizers.Adam(lr= 2*1e-4)

In [163]:
embedding_size = 128
n_classes = 3
epochs = 30

model = keras.Sequential()
model.add(Embedding(num_words, embedding_size, input_shape=(max_len,)))

# model.add(Dropout(0.25))
# model.add(LSTM(64, kernel_initializer='glorot_normal', recurrent_initializer='glorot_normal', activation='relu', return_sequences=True))
# model.add(Dropout(0.3))
model.add(LSTM(64, kernel_initializer='glorot_normal', recurrent_initializer='glorot_normal', activation='sigmoid'))
# model.add(Dropout(0.2))
# model.add(Flatten())
# model.add(Dense(64, activation='relu'))
# model.add(Dense(50, activation='relu'))
# model.add(Dropout(0.3))

# model.add(GRU(64))
# model.add(Dropout(0.3))

model.add(Dense(3, activation='softmax'))
model.compile(optimizer, 'sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_29 (Embedding)     (None, 20, 128)           256000    
_________________________________________________________________
lstm_14 (LSTM)               (None, 64)                49408     
_________________________________________________________________
dense_25 (Dense)             (None, 3)                 195       
Total params: 305,603
Trainable params: 305,603
Non-trainable params: 0
_________________________________________________________________


In [0]:
callback = keras.callbacks.EarlyStopping(monitor='val_loss', min_delta=0, patience=1)

In [165]:
model.fit(x_train, np.array(y_train), epochs= 50, validation_split=0.15, callbacks= [callback], batch_size=32)

Train on 5418 samples, validate on 957 samples
Epoch 1/50
5418/5418 [==============================] - 15s 3ms/step - loss: 1.1113 - acc: 0.3472 - val_loss: 1.0964 - val_acc: 0.3720
Epoch 2/50
5418/5418 [==============================] - 11s 2ms/step - loss: 1.0954 - acc: 0.3562 - val_loss: 1.0956 - val_acc: 0.3281
Epoch 3/50
5418/5418 [==============================] - 11s 2ms/step - loss: 1.0912 - acc: 0.3680 - val_loss: 1.0894 - val_acc: 0.3511
Epoch 4/50
5418/5418 [==============================] - 11s 2ms/step - loss: 1.0848 - acc: 0.3852 - val_loss: 1.0880 - val_acc: 0.3605
Epoch 5/50
5418/5418 [==============================] - 11s 2ms/step - loss: 1.0762 - acc: 0.3970 - val_loss: 1.0798 - val_acc: 0.3866
Epoch 6/50
5418/5418 [==============================] - 11s 2ms/step - loss: 1.0631 - acc: 0.4219 - val_loss: 1.0686 - val_acc: 0.4148
Epoch 7/50
5418/5418 [==============================] - 11s 2ms/step - loss: 1.0398 - acc: 0.4683 - val_loss: 1.0478 - val_acc: 0.4368
Epoch 8/

In [166]:
model.evaluate(x_test, np.array(y_test))

1125/1125 [==============================] - 1s 769us/step


[0.5054080916908053, 0.8]

In [0]:
model.save('books_classification_lstm.h5')

#### LSTM test accuracy: 80%



### Model on Browser

In [0]:
# your github username
USER_NAME = "Srinidhi-kv" 

# the email associated with your commits
# (may not matter if you leave it as this)
USER_EMAIL = "sk4356@columbia.edu" 

# the user token you've created (see the lecture 8 slides for instructions)
TOKEN = "e0c2a9d915b1e08557d28b88764f47fa44a84628" 

# site name
# for example, if my user_name is "foo", then this notebook will create
# a site at https://foo.github.io/hw4/
SITE_NAME = "deep_learning_hw4"

In [0]:
!git config --global user.email {USER_NAME}
!git config --global user.name  {USER_EMAIL}

In [124]:
repo_path = USER_NAME + '.github.io'
if not os.path.exists(os.path.join(os.getcwd(), repo_path)):
  !git clone https://{USER_NAME}:{TOKEN}@github.com/{USER_NAME}/{USER_NAME}.github.io

Cloning into 'Srinidhi-kv.github.io'...
remote: Enumerating objects: 32, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 32 (delta 7), reused 28 (delta 6), pack-reused 0
Unpacking objects: 100% (32/32), done.


In [125]:
os.chdir(repo_path)
!git pull

Already up to date.


In [0]:
project_path = os.path.join(os.getcwd(), SITE_NAME)
if not os.path.exists(project_path): 
  os.mkdir(project_path)
os.chdir(project_path)

In [0]:
# DO NOT MODIFY
MODEL_DIR = os.path.join(project_path, "model_js")
if not os.path.exists(MODEL_DIR):
  os.mkdir(MODEL_DIR)

In [0]:
test_example = ' One of my last thoughts was of the captain, who had so often strode along the beachwith his cocked hat, his sabre-cut cheek, and his old brass telescope'
x_test = t.texts_to_sequences([test_example])
x_test = pad_sequences(x_test, maxlen=max_len, padding='post')

In [129]:
preds = model.predict(x_test)
# print(preds)
print(np.argmax(preds))

0


In [0]:
metadata = {
  'word_index': t.word_index,
  'max_len': max_len,
  'vocabulary_size': num_words,
}

In [131]:
import json
import tensorflowjs as tfjs

metadata_json_path = os.path.join(MODEL_DIR, 'metadata.json')
json.dump(metadata, open(metadata_json_path, 'wt'))
tfjs.converters.save_keras_model(model, MODEL_DIR)
print('\nSaved model artifcats in directory: %s' % MODEL_DIR)


Saved model artifcats in directory: /content/Srinidhi-kv.github.io/deep_learning_hw4/model_js


In [0]:
index_html = """
<!doctype html>

<body>
  <style>
    #textfield {
      font-size: 120%;
      width: 60%;
      height: 200px;
    }
  </style>
  <h1>
    Title
  </h1>
  <hr>
  <div class="create-model">
    <button id="load-model" style="display:none">Load model</button>
  </div>
  <div>
    <div>
      <span>Vocabulary size: </span>
      <span id="vocabularySize"></span>
    </div>
    <div>
      <span>Max length: </span>
      <span id="maxLen"></span>
    </div>
  </div>
  <hr>
  <div>
    <select id="example-select" class="form-control">
      <option value="example1">Treasure Island</option>
      <option value="example2">Count of Monte Carlo</option>
      <option value="example3">Sherlock Holmes</option>
    </select>
  </div>
  <div>
    <textarea id="text-entry"></textarea>
  </div>
  <hr>
  <div>
    <span id="status">Standing by.</span>
  </div>

  <script src='https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js'></script>
  <script src='index.js'></script>
</body>
"""

In [0]:
index_js = """
const HOSTED_URLS = {
  model:
      'model_js/model.json',
  metadata:
      'model_js/metadata.json'
};

const examples = {
  'example1':
      ' One of my lastthoughts was of the captain, who had so often strode along the beachwith his cocked hat, his sabre-cut cheek, and his old brass telescope',
  'example2':
      ' Here is thepaper; do you know the writing?” As he spoke, Villefort drew the letterfrom his pocket, and presented it to Dantès',
  'example3':
      'But how could you guess what the motive was?'      
};

function status(statusText) {
  console.log(statusText);
  document.getElementById('status').textContent = statusText;
}

function showMetadata(metadataJSON) {
  document.getElementById('vocabularySize').textContent =
      metadataJSON['vocabulary_size'];
  document.getElementById('maxLen').textContent =
      metadataJSON['max_len'];
}

function settextField(text, predict) {
  const textField = document.getElementById('text-entry');
  textField.value = text;
  doPredict(predict);
}

function setPredictFunction(predict) {
  const textField = document.getElementById('text-entry');
  textField.addEventListener('input', () => doPredict(predict));
}

function disableLoadModelButtons() {
  document.getElementById('load-model').style.display = 'none';
}

function doPredict(predict) {
  const textField = document.getElementById('text-entry');
  const result = predict(textField.value);
  score_string = "Class scores: ";
  for (var x in result.score) {
    score_string += x + " ->  " + result.score[x].toFixed(3) + ", "
  }
  //console.log(score_string);
  status(
      score_string + ' elapsed: ' + result.elapsed.toFixed(3) + ' ms)');
}

function prepUI(predict) {
  setPredictFunction(predict);
  const testExampleSelect = document.getElementById('example-select');
  testExampleSelect.addEventListener('change', () => {
    settextField(examples[testExampleSelect.value], predict);
  });
  settextField(examples['example1'], predict);
}

async function urlExists(url) {
  status('Testing url ' + url);
  try {
    const response = await fetch(url, {method: 'HEAD'});
    return response.ok;
  } catch (err) {
    return false;
  }
}

async function loadHostedPretrainedModel(url) {
  status('Loading pretrained model from ' + url);
  try {
    const model = await tf.loadModel(url);
    status('Done loading pretrained model.');
    disableLoadModelButtons();
    return model;
  } catch (err) {
    console.error(err);
    status('Loading pretrained model failed.');
  }
}

async function loadHostedMetadata(url) {
  status('Loading metadata from ' + url);
  try {
    const metadataJson = await fetch(url);
    const metadata = await metadataJson.json();
    status('Done loading metadata.');
    return metadata;
  } catch (err) {
    console.error(err);
    status('Loading metadata failed.');
  }
}

class Classifier {

  async init(urls) {
    this.urls = urls;
    this.model = await loadHostedPretrainedModel(urls.model);
    await this.loadMetadata();
    return this;
  }

  async loadMetadata() {
    const metadata =
        await loadHostedMetadata(this.urls.metadata);
    showMetadata(metadata);
    this.maxLen = metadata['max_len'];
    console.log('maxLen = ' + this.maxLen);
    this.wordIndex = metadata['word_index']
  }

  predict(text) {
    // Convert to lower case and remove all punctuations.
    const inputText =
        text.trim().toLowerCase().replace(/(\.|\,|\!)/g, '').split(' ');
    // Look up word indices.
    const inputBuffer = tf.buffer([1, this.maxLen], 'float32');
    for (let i = 0; i < inputText.length; ++i) {
      const word = inputText[i];
      inputBuffer.set(this.wordIndex[word], 0, i);
      //console.log(word, this.wordIndex[word], inputBuffer);
    }
    const input = inputBuffer.toTensor();
    //console.log(input);

    status('Running inference');
    const beginMs = performance.now();
    const predictOut = this.model.predict(input);
    //console.log(predictOut.dataSync());
    const score = predictOut.dataSync();//[0];
    predictOut.dispose();
    const endMs = performance.now();

    return {score: score, elapsed: (endMs - beginMs)};
  }
};

async function setup() {
  if (await urlExists(HOSTED_URLS.model)) {
    status('Model available: ' + HOSTED_URLS.model);
    const button = document.getElementById('load-model');
    button.addEventListener('click', async () => {
      const predictor = await new Classifier().init(HOSTED_URLS);
      prepUI(x => predictor.predict(x));
    });
    button.style.display = 'inline-block';
  }

  status('Standing by.');
}

setup();
"""

In [0]:
with open('index.html','w') as f:
  f.write(index_html)
  
with open('index.js','w') as f:
  f.write(index_js)

In [135]:
!git add . 
!git commit -m "colab -> github"
!git push https://{USER_NAME}:{TOKEN}@github.com/{USER_NAME}/{USER_NAME}.github.io/ master

[master b1dfbfe] colab -> github
 3 files changed, 2 insertions(+), 2 deletions(-)
 rewrite deep_learning_hw4/model_js/group1-shard1of1 (84%)
 rewrite deep_learning_hw4/model_js/model.json (92%)
Counting objects: 7, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 1.08 MiB | 1.47 MiB/s, done.
Total 7 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/Srinidhi-kv/Srinidhi-kv.github.io/
   8a88de5..b1dfbfe  master -> master


In [0]:
print("Now, visit https://%s.github.io/%s/" % (USER_NAME, SITE_NAME))

Now, visit https://Srinidhi-kv.github.io/deep_learning_hw4/
